# mfa_protocol.py

UART_BAUD = 115200
UART_TIMEOUT_MS = 8000

NONCE_HEX_LEN = 32
PUBKEY_HEX_LEN = 64
PROOF_HEX_LEN = 64

PREFIX_STATUS_OK = b"MFA:STATUS:OK:"
PREFIX_ERR = b"MFA:ERR:"
PREFIX_ENROLL_OK = b"MFA:ENROLL:OK:"
PREFIX_PROOF_OK = b"MFA:PROOF:OK:"
PREFIX_PUBKEY_OK = b"MFA:PUBKEY:OK:"
PREFIX_WORK = b"MFA:WORK:"

CMD_STATUS = b"MFA:STATUS?\n"
CMD_ENROLL = b"MFA:ENROLL:"
CMD_AUTH = b"MFA:AUTH:"
CMD_PUBKEY = b"MFA:PUBKEY?\n"
